USE alx_book_store:

CREATE TABLE IF NOT EXISTS AUTHORS (
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR NAME VARCHAR(100) NOT NULL,
    BIO TEXT
):

CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID INIT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INIT,
    PRICE DECIMAL(10, 2),
    PUBLISHED_DATE DATE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
):

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INIT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    ADDRESS TEXT
):

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INIT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INIT,
    ORDER_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
):

CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDER_DETAIL_ID INIT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INIT,
    BOOK_ID INIT,
    QUANTITY INIT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
):